---
dataset_index:
  - "ROI"
  - "tile"
  - "patch"
  - "timestep"

modalities:
  - "S1"
  - "S2"
  - "S2CLOUDMAP"

filepath_metadata:
  - "ROI"
  - "tile"
  - "modality"
  - "timestep"

filename_metadata:
  - "modality"
  - "ROI"
  - "tile"
  - "timestep"
  - "date"
  - "patch"

band_definition:
  "S1": "polarization"
  "S2": "band"

bands:
  "S1":
    - "VV"
    - "VH"
  "S2":
    - "B01"
    - "B02"
    - "B03"
    - "B04"
    - "B05"
    - "B06"
    - "B07"
    - "B08"
    - "B8A"
    - "B09"
    - "B10"
    - "B11"
    - "B12"
